module.exports = {
  AUTH0_CLIENT_SECRET : 'AUTH0_CLIENT_SECRET',
  NODEMAILER_PASSWORD : 'NODEMAILER_PASSWORD',
  GOOGLE_CALENDAR_ID : 'GOOGLE_CALENDAR_ID',
  GOOGLE_CLIENT_SECRET : 'GOOGLE_CLIENT_SECRET',
  DEPLOYED : DEPLOYED
};
